version: '3.8'
services:

  redmine:
    image: redmine:$APP_VERSION
    container_name: $APP_CONTAINER_NAME
    restart: always
    ports:
     - $APP_PORT:3000
    volumes: 
     - $VOLUMES_PATH_PREFIX/data/:/usr/src/redmine/files
     - $VOLUMES_PATH_PREFIX/plugins:/usr/src/redmine/plugins
     - $VOLUMES_PATH_PREFIX/themes:/usr/src/redmine/public/themes
     - $VOLUMES_PATH_PREFIX/config/configuration.yml:/usr/src/redmine/config/configuration.yml
    environment:
      REDMINE_DB_MYSQL: $DB_MYSQL_HOST
      REDMINE_DB_PASSWORD: $DB_MYSQL_PASSWORD
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_PLUGINS_MIGRATE: "true"

  db:
    image: mysql:$DB_MYSQL_VERSION
    container_name: $APP_CONTAINER_NAME-mysql
    restart: always
    ports:
     - $DB_MYSQL_PORT:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
     - $VOLUMES_PATH_PREFIX/mysql_config/conf.d:/etc/mysql/conf.d
     - $VOLUMES_PATH_PREFIX/mysql_data:/var/lib/mysql
     - $VOLUMES_PATH_PREFIX/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_PASSWORD
      MYSQL_DATABASE: $DB_MYSQL_NAME

networks:
  default:
      name: "$APP_NETWORK"

